#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 91
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 55
#define ALIAS_COUNT 0
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 13
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 8

enum ts_symbol_identifiers {
  anon_sym_DASH_DASH_DASH = 1,
  anon_sym_PERCENTdw = 2,
  anon_sym_output = 3,
  anon_sym_import = 4,
  anon_sym_from = 5,
  anon_sym_null = 6,
  aux_sym_variable_token1 = 7,
  anon_sym_LPAREN = 8,
  anon_sym_COMMA = 9,
  anon_sym_RPAREN = 10,
  anon_sym_LBRACE = 11,
  anon_sym_RBRACE = 12,
  anon_sym_COLON = 13,
  anon_sym_LBRACK = 14,
  anon_sym_RBRACK = 15,
  anon_sym_if = 16,
  anon_sym_else = 17,
  anon_sym_PLUS = 18,
  anon_sym_DASH = 19,
  anon_sym_STAR = 20,
  anon_sym_SLASH = 21,
  anon_sym_PERCENT = 22,
  anon_sym_EQ_EQ = 23,
  anon_sym_BANG_EQ = 24,
  anon_sym_LT = 25,
  anon_sym_GT = 26,
  anon_sym_LT_EQ = 27,
  anon_sym_GT_EQ = 28,
  anon_sym_and = 29,
  anon_sym_or = 30,
  sym_number = 31,
  sym_string = 32,
  anon_sym_true = 33,
  anon_sym_false = 34,
  sym_source_file = 35,
  sym_header = 36,
  sym_output_directive = 37,
  sym_import_directive = 38,
  sym_body = 39,
  sym__expression = 40,
  sym_literal = 41,
  sym_variable = 42,
  sym_function_call = 43,
  sym_object = 44,
  sym_key_value_pair = 45,
  sym_array = 46,
  sym_if_expression = 47,
  sym_binary_expression = 48,
  sym_identifier = 49,
  sym_boolean = 50,
  aux_sym_header_repeat1 = 51,
  aux_sym_body_repeat1 = 52,
  aux_sym_function_call_repeat1 = 53,
  aux_sym_object_repeat1 = 54,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DASH_DASH_DASH] = "---",
  [anon_sym_PERCENTdw] = "%dw",
  [anon_sym_output] = "output",
  [anon_sym_import] = "import",
  [anon_sym_from] = "from",
  [anon_sym_null] = "null",
  [aux_sym_variable_token1] = "variable_token1",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_and] = "and",
  [anon_sym_or] = "or",
  [sym_number] = "number",
  [sym_string] = "string",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_source_file] = "source_file",
  [sym_header] = "header",
  [sym_output_directive] = "output_directive",
  [sym_import_directive] = "import_directive",
  [sym_body] = "body",
  [sym__expression] = "_expression",
  [sym_literal] = "literal",
  [sym_variable] = "variable",
  [sym_function_call] = "function_call",
  [sym_object] = "object",
  [sym_key_value_pair] = "key_value_pair",
  [sym_array] = "array",
  [sym_if_expression] = "if_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_identifier] = "identifier",
  [sym_boolean] = "boolean",
  [aux_sym_header_repeat1] = "header_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
  [aux_sym_object_repeat1] = "object_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DASH_DASH_DASH] = anon_sym_DASH_DASH_DASH,
  [anon_sym_PERCENTdw] = anon_sym_PERCENTdw,
  [anon_sym_output] = anon_sym_output,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_from] = anon_sym_from,
  [anon_sym_null] = anon_sym_null,
  [aux_sym_variable_token1] = aux_sym_variable_token1,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_or] = anon_sym_or,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_source_file] = sym_source_file,
  [sym_header] = sym_header,
  [sym_output_directive] = sym_output_directive,
  [sym_import_directive] = sym_import_directive,
  [sym_body] = sym_body,
  [sym__expression] = sym__expression,
  [sym_literal] = sym_literal,
  [sym_variable] = sym_variable,
  [sym_function_call] = sym_function_call,
  [sym_object] = sym_object,
  [sym_key_value_pair] = sym_key_value_pair,
  [sym_array] = sym_array,
  [sym_if_expression] = sym_if_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_identifier] = sym_identifier,
  [sym_boolean] = sym_boolean,
  [aux_sym_header_repeat1] = aux_sym_header_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
  [aux_sym_object_repeat1] = aux_sym_object_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DASH_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENTdw] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_output] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_from] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_null] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_variable_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_output_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_import_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_key_value_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_if_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_header_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_alternative = 1,
  field_condition = 2,
  field_consequence = 3,
  field_key = 4,
  field_left = 5,
  field_location = 6,
  field_mime_type = 7,
  field_module = 8,
  field_name = 9,
  field_operator = 10,
  field_right = 11,
  field_value = 12,
  field_version = 13,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alternative] = "alternative",
  [field_condition] = "condition",
  [field_consequence] = "consequence",
  [field_key] = "key",
  [field_left] = "left",
  [field_location] = "location",
  [field_mime_type] = "mime_type",
  [field_module] = "module",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_right] = "right",
  [field_value] = "value",
  [field_version] = "version",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 3},
  [3] = {.index = 4, .length = 1},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 3},
  [7] = {.index = 11, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_version, 1},
  [1] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [4] =
    {field_name, 0},
  [5] =
    {field_mime_type, 1},
  [6] =
    {field_key, 0},
    {field_value, 2},
  [8] =
    {field_alternative, 4},
    {field_condition, 1},
    {field_consequence, 2},
  [11] =
    {field_location, 3},
    {field_module, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 23,
  [26] = 24,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 29,
  [31] = 27,
  [32] = 4,
  [33] = 28,
  [34] = 34,
  [35] = 35,
  [36] = 5,
  [37] = 18,
  [38] = 6,
  [39] = 10,
  [40] = 15,
  [41] = 17,
  [42] = 14,
  [43] = 7,
  [44] = 8,
  [45] = 9,
  [46] = 13,
  [47] = 12,
  [48] = 16,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 49,
  [53] = 50,
  [54] = 54,
  [55] = 55,
  [56] = 55,
  [57] = 57,
  [58] = 58,
  [59] = 58,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 67,
  [69] = 69,
  [70] = 70,
  [71] = 66,
  [72] = 70,
  [73] = 73,
  [74] = 73,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 84,
  [89] = 89,
  [90] = 90,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(44);
      ADVANCE_MAP(
        '!', 7,
        '"', 3,
        '%', 83,
        '(', 67,
        ')', 69,
        '*', 81,
        '+', 78,
        ',', 68,
        '-', 80,
        '/', 82,
        ':', 72,
        '<', 86,
        '=', 8,
        '>', 87,
        '[', 73,
        ']', 74,
        'a', 22,
        'e', 16,
        'f', 9,
        'i', 15,
        'n', 37,
        'o', 28,
        't', 29,
        '{', 70,
        '}', 71,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(94);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 7,
        '%', 83,
        '(', 67,
        ')', 69,
        '*', 81,
        '+', 78,
        ',', 68,
        '-', 79,
        '/', 82,
        '<', 86,
        '=', 8,
        '>', 87,
        ']', 74,
        'a', 22,
        'e', 16,
        'o', 27,
        '}', 71,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '}') ADVANCE(71);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(96);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(45);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == 'i') ADVANCE(20);
      if (lookahead == 'o') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(85);
      END_STATE();
    case 8:
      if (lookahead == '=') ADVANCE(84);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(19);
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(90);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(40);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(77);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(97);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(99);
      END_STATE();
    case 15:
      if (lookahead == 'f') ADVANCE(75);
      if (lookahead == 'm') ADVANCE(25);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(31);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(50);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(25);
      END_STATE();
    case 21:
      if (lookahead == 'm') ADVANCE(49);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 25:
      if (lookahead == 'p') ADVANCE(24);
      END_STATE();
    case 26:
      if (lookahead == 'p') ADVANCE(39);
      END_STATE();
    case 27:
      if (lookahead == 'r') ADVANCE(92);
      END_STATE();
    case 28:
      if (lookahead == 'r') ADVANCE(92);
      if (lookahead == 'u') ADVANCE(35);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(38);
      END_STATE();
    case 30:
      if (lookahead == 'r') ADVANCE(33);
      END_STATE();
    case 31:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 32:
      if (lookahead == 's') ADVANCE(14);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(48);
      END_STATE();
    case 34:
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 36:
      if (lookahead == 'u') ADVANCE(35);
      END_STATE();
    case 37:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 38:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 39:
      if (lookahead == 'u') ADVANCE(34);
      END_STATE();
    case 40:
      if (lookahead == 'w') ADVANCE(46);
      END_STATE();
    case 41:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(95);
      END_STATE();
    case 42:
      if (eof) ADVANCE(44);
      ADVANCE_MAP(
        '!', 7,
        '"', 3,
        '%', 83,
        '(', 67,
        '*', 81,
        '+', 78,
        '-', 79,
        '/', 82,
        '<', 86,
        '=', 8,
        '>', 87,
        '[', 73,
        'a', 60,
        'f', 52,
        'i', 56,
        'n', 65,
        'o', 61,
        't', 62,
        '{', 70,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(94);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 43:
      if (eof) ADVANCE(44);
      ADVANCE_MAP(
        '"', 3,
        '%', 11,
        ')', 69,
        '-', 4,
        '[', 73,
        ']', 74,
        'f', 52,
        'i', 56,
        'n', 65,
        't', 62,
        '{', 70,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(43);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(94);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_DASH);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_PERCENTdw);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_output);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_from);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_null);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_null);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_variable_token1);
      if (lookahead == 'a') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_variable_token1);
      if (lookahead == 'd') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_variable_token1);
      if (lookahead == 'e') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_variable_token1);
      if (lookahead == 'e') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_variable_token1);
      if (lookahead == 'f') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_variable_token1);
      if (lookahead == 'l') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_variable_token1);
      if (lookahead == 'l') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_variable_token1);
      if (lookahead == 'l') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_variable_token1);
      if (lookahead == 'n') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_variable_token1);
      if (lookahead == 'r') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_variable_token1);
      if (lookahead == 'r') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_variable_token1);
      if (lookahead == 's') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_variable_token1);
      if (lookahead == 'u') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_variable_token1);
      if (lookahead == 'u') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_variable_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(88);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(89);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_and);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_or);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(94);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(95);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 43},
  [2] = {.lex_state = 42},
  [3] = {.lex_state = 42},
  [4] = {.lex_state = 42},
  [5] = {.lex_state = 42},
  [6] = {.lex_state = 42},
  [7] = {.lex_state = 42},
  [8] = {.lex_state = 42},
  [9] = {.lex_state = 42},
  [10] = {.lex_state = 42},
  [11] = {.lex_state = 42},
  [12] = {.lex_state = 42},
  [13] = {.lex_state = 42},
  [14] = {.lex_state = 42},
  [15] = {.lex_state = 42},
  [16] = {.lex_state = 42},
  [17] = {.lex_state = 42},
  [18] = {.lex_state = 42},
  [19] = {.lex_state = 43},
  [20] = {.lex_state = 43},
  [21] = {.lex_state = 43},
  [22] = {.lex_state = 43},
  [23] = {.lex_state = 43},
  [24] = {.lex_state = 43},
  [25] = {.lex_state = 43},
  [26] = {.lex_state = 43},
  [27] = {.lex_state = 43},
  [28] = {.lex_state = 43},
  [29] = {.lex_state = 43},
  [30] = {.lex_state = 43},
  [31] = {.lex_state = 43},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 43},
  [34] = {.lex_state = 43},
  [35] = {.lex_state = 43},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 6},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 6},
  [63] = {.lex_state = 6},
  [64] = {.lex_state = 6},
  [65] = {.lex_state = 6},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 6},
  [79] = {.lex_state = 6},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 43},
  [90] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DASH_DASH_DASH] = ACTIONS(1),
    [anon_sym_output] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_from] = ACTIONS(1),
    [anon_sym_null] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(90),
    [sym_header] = STATE(89),
    [anon_sym_DASH_DASH_DASH] = ACTIONS(3),
    [anon_sym_PERCENTdw] = ACTIONS(5),
  },
  [2] = {
    [sym__expression] = STATE(56),
    [sym_literal] = STATE(56),
    [sym_variable] = STATE(56),
    [sym_function_call] = STATE(56),
    [sym_object] = STATE(56),
    [sym_array] = STATE(56),
    [sym_if_expression] = STATE(56),
    [sym_binary_expression] = STATE(56),
    [sym_identifier] = STATE(88),
    [sym_boolean] = STATE(43),
    [anon_sym_null] = ACTIONS(7),
    [aux_sym_variable_token1] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_PLUS] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_STAR] = ACTIONS(17),
    [anon_sym_SLASH] = ACTIONS(17),
    [anon_sym_PERCENT] = ACTIONS(17),
    [anon_sym_EQ_EQ] = ACTIONS(17),
    [anon_sym_BANG_EQ] = ACTIONS(17),
    [anon_sym_LT] = ACTIONS(19),
    [anon_sym_GT] = ACTIONS(19),
    [anon_sym_LT_EQ] = ACTIONS(17),
    [anon_sym_GT_EQ] = ACTIONS(17),
    [anon_sym_and] = ACTIONS(19),
    [anon_sym_or] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
  },
  [3] = {
    [sym__expression] = STATE(55),
    [sym_literal] = STATE(55),
    [sym_variable] = STATE(55),
    [sym_function_call] = STATE(55),
    [sym_object] = STATE(55),
    [sym_array] = STATE(55),
    [sym_if_expression] = STATE(55),
    [sym_binary_expression] = STATE(55),
    [sym_identifier] = STATE(88),
    [sym_boolean] = STATE(43),
    [anon_sym_null] = ACTIONS(7),
    [aux_sym_variable_token1] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_PLUS] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_STAR] = ACTIONS(17),
    [anon_sym_SLASH] = ACTIONS(17),
    [anon_sym_PERCENT] = ACTIONS(17),
    [anon_sym_EQ_EQ] = ACTIONS(17),
    [anon_sym_BANG_EQ] = ACTIONS(17),
    [anon_sym_LT] = ACTIONS(19),
    [anon_sym_GT] = ACTIONS(19),
    [anon_sym_LT_EQ] = ACTIONS(17),
    [anon_sym_GT_EQ] = ACTIONS(17),
    [anon_sym_and] = ACTIONS(19),
    [anon_sym_or] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 9,
      anon_sym_null,
      aux_sym_variable_token1,
      anon_sym_if,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 14,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_number,
      sym_string,
  [31] = 2,
    ACTIONS(33), 9,
      anon_sym_null,
      aux_sym_variable_token1,
      anon_sym_if,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(31), 14,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_number,
      sym_string,
  [59] = 2,
    ACTIONS(37), 9,
      anon_sym_null,
      aux_sym_variable_token1,
      anon_sym_if,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(35), 14,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_number,
      sym_string,
  [87] = 2,
    ACTIONS(41), 9,
      anon_sym_null,
      aux_sym_variable_token1,
      anon_sym_if,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(39), 14,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_number,
      sym_string,
  [115] = 2,
    ACTIONS(45), 9,
      anon_sym_null,
      aux_sym_variable_token1,
      anon_sym_if,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(43), 14,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_number,
      sym_string,
  [143] = 2,
    ACTIONS(49), 9,
      anon_sym_null,
      aux_sym_variable_token1,
      anon_sym_if,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(47), 14,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_number,
      sym_string,
  [171] = 2,
    ACTIONS(53), 9,
      anon_sym_null,
      aux_sym_variable_token1,
      anon_sym_if,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(51), 14,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_number,
      sym_string,
  [199] = 4,
    ACTIONS(19), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
    ACTIONS(55), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      sym_number,
      sym_string,
    ACTIONS(57), 5,
      anon_sym_null,
      aux_sym_variable_token1,
      anon_sym_if,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(17), 9,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [231] = 2,
    ACTIONS(61), 9,
      anon_sym_null,
      aux_sym_variable_token1,
      anon_sym_if,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(59), 14,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_number,
      sym_string,
  [259] = 2,
    ACTIONS(65), 9,
      anon_sym_null,
      aux_sym_variable_token1,
      anon_sym_if,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(63), 14,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_number,
      sym_string,
  [287] = 2,
    ACTIONS(69), 9,
      anon_sym_null,
      aux_sym_variable_token1,
      anon_sym_if,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(67), 14,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_number,
      sym_string,
  [315] = 2,
    ACTIONS(73), 9,
      anon_sym_null,
      aux_sym_variable_token1,
      anon_sym_if,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(71), 14,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_number,
      sym_string,
  [343] = 2,
    ACTIONS(77), 9,
      anon_sym_null,
      aux_sym_variable_token1,
      anon_sym_if,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(75), 14,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_number,
      sym_string,
  [371] = 4,
    ACTIONS(19), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
    ACTIONS(79), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      sym_number,
      sym_string,
    ACTIONS(81), 5,
      anon_sym_null,
      aux_sym_variable_token1,
      anon_sym_if,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(17), 9,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [403] = 2,
    ACTIONS(85), 9,
      anon_sym_null,
      aux_sym_variable_token1,
      anon_sym_if,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(83), 14,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_number,
      sym_string,
  [431] = 12,
    ACTIONS(87), 1,
      anon_sym_null,
    ACTIONS(89), 1,
      aux_sym_variable_token1,
    ACTIONS(91), 1,
      anon_sym_LBRACE,
    ACTIONS(93), 1,
      anon_sym_LBRACK,
    ACTIONS(95), 1,
      anon_sym_if,
    STATE(7), 1,
      sym_boolean,
    STATE(21), 1,
      aux_sym_body_repeat1,
    STATE(80), 1,
      sym_body,
    STATE(84), 1,
      sym_identifier,
    ACTIONS(97), 2,
      sym_number,
      sym_string,
    ACTIONS(99), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(11), 8,
      sym__expression,
      sym_literal,
      sym_variable,
      sym_function_call,
      sym_object,
      sym_array,
      sym_if_expression,
      sym_binary_expression,
  [477] = 12,
    ACTIONS(101), 1,
      ts_builtin_sym_end,
    ACTIONS(103), 1,
      anon_sym_null,
    ACTIONS(106), 1,
      aux_sym_variable_token1,
    ACTIONS(109), 1,
      anon_sym_LBRACE,
    ACTIONS(112), 1,
      anon_sym_LBRACK,
    ACTIONS(115), 1,
      anon_sym_if,
    STATE(7), 1,
      sym_boolean,
    STATE(20), 1,
      aux_sym_body_repeat1,
    STATE(84), 1,
      sym_identifier,
    ACTIONS(118), 2,
      sym_number,
      sym_string,
    ACTIONS(121), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(11), 8,
      sym__expression,
      sym_literal,
      sym_variable,
      sym_function_call,
      sym_object,
      sym_array,
      sym_if_expression,
      sym_binary_expression,
  [523] = 12,
    ACTIONS(87), 1,
      anon_sym_null,
    ACTIONS(89), 1,
      aux_sym_variable_token1,
    ACTIONS(91), 1,
      anon_sym_LBRACE,
    ACTIONS(93), 1,
      anon_sym_LBRACK,
    ACTIONS(95), 1,
      anon_sym_if,
    ACTIONS(124), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      sym_boolean,
    STATE(20), 1,
      aux_sym_body_repeat1,
    STATE(84), 1,
      sym_identifier,
    ACTIONS(97), 2,
      sym_number,
      sym_string,
    ACTIONS(99), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(11), 8,
      sym__expression,
      sym_literal,
      sym_variable,
      sym_function_call,
      sym_object,
      sym_array,
      sym_if_expression,
      sym_binary_expression,
  [569] = 12,
    ACTIONS(87), 1,
      anon_sym_null,
    ACTIONS(89), 1,
      aux_sym_variable_token1,
    ACTIONS(91), 1,
      anon_sym_LBRACE,
    ACTIONS(93), 1,
      anon_sym_LBRACK,
    ACTIONS(95), 1,
      anon_sym_if,
    STATE(7), 1,
      sym_boolean,
    STATE(21), 1,
      aux_sym_body_repeat1,
    STATE(83), 1,
      sym_body,
    STATE(84), 1,
      sym_identifier,
    ACTIONS(97), 2,
      sym_number,
      sym_string,
    ACTIONS(99), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(11), 8,
      sym__expression,
      sym_literal,
      sym_variable,
      sym_function_call,
      sym_object,
      sym_array,
      sym_if_expression,
      sym_binary_expression,
  [615] = 11,
    ACTIONS(7), 1,
      anon_sym_null,
    ACTIONS(9), 1,
      aux_sym_variable_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(126), 1,
      anon_sym_RBRACK,
    STATE(43), 1,
      sym_boolean,
    STATE(88), 1,
      sym_identifier,
    ACTIONS(21), 2,
      sym_number,
      sym_string,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(49), 8,
      sym__expression,
      sym_literal,
      sym_variable,
      sym_function_call,
      sym_object,
      sym_array,
      sym_if_expression,
      sym_binary_expression,
  [658] = 11,
    ACTIONS(7), 1,
      anon_sym_null,
    ACTIONS(9), 1,
      aux_sym_variable_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(128), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      sym_boolean,
    STATE(88), 1,
      sym_identifier,
    ACTIONS(21), 2,
      sym_number,
      sym_string,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(53), 8,
      sym__expression,
      sym_literal,
      sym_variable,
      sym_function_call,
      sym_object,
      sym_array,
      sym_if_expression,
      sym_binary_expression,
  [701] = 11,
    ACTIONS(7), 1,
      anon_sym_null,
    ACTIONS(9), 1,
      aux_sym_variable_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(130), 1,
      anon_sym_RBRACK,
    STATE(43), 1,
      sym_boolean,
    STATE(88), 1,
      sym_identifier,
    ACTIONS(21), 2,
      sym_number,
      sym_string,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(52), 8,
      sym__expression,
      sym_literal,
      sym_variable,
      sym_function_call,
      sym_object,
      sym_array,
      sym_if_expression,
      sym_binary_expression,
  [744] = 11,
    ACTIONS(7), 1,
      anon_sym_null,
    ACTIONS(9), 1,
      aux_sym_variable_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(132), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      sym_boolean,
    STATE(88), 1,
      sym_identifier,
    ACTIONS(21), 2,
      sym_number,
      sym_string,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(50), 8,
      sym__expression,
      sym_literal,
      sym_variable,
      sym_function_call,
      sym_object,
      sym_array,
      sym_if_expression,
      sym_binary_expression,
  [787] = 10,
    ACTIONS(87), 1,
      anon_sym_null,
    ACTIONS(89), 1,
      aux_sym_variable_token1,
    ACTIONS(91), 1,
      anon_sym_LBRACE,
    ACTIONS(93), 1,
      anon_sym_LBRACK,
    ACTIONS(95), 1,
      anon_sym_if,
    STATE(7), 1,
      sym_boolean,
    STATE(84), 1,
      sym_identifier,
    ACTIONS(97), 2,
      sym_number,
      sym_string,
    ACTIONS(99), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(3), 8,
      sym__expression,
      sym_literal,
      sym_variable,
      sym_function_call,
      sym_object,
      sym_array,
      sym_if_expression,
      sym_binary_expression,
  [827] = 10,
    ACTIONS(87), 1,
      anon_sym_null,
    ACTIONS(89), 1,
      aux_sym_variable_token1,
    ACTIONS(91), 1,
      anon_sym_LBRACE,
    ACTIONS(93), 1,
      anon_sym_LBRACK,
    ACTIONS(95), 1,
      anon_sym_if,
    STATE(7), 1,
      sym_boolean,
    STATE(84), 1,
      sym_identifier,
    ACTIONS(97), 2,
      sym_number,
      sym_string,
    ACTIONS(99), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(8), 8,
      sym__expression,
      sym_literal,
      sym_variable,
      sym_function_call,
      sym_object,
      sym_array,
      sym_if_expression,
      sym_binary_expression,
  [867] = 10,
    ACTIONS(7), 1,
      anon_sym_null,
    ACTIONS(9), 1,
      aux_sym_variable_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_if,
    STATE(43), 1,
      sym_boolean,
    STATE(88), 1,
      sym_identifier,
    ACTIONS(21), 2,
      sym_number,
      sym_string,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(41), 8,
      sym__expression,
      sym_literal,
      sym_variable,
      sym_function_call,
      sym_object,
      sym_array,
      sym_if_expression,
      sym_binary_expression,
  [907] = 10,
    ACTIONS(87), 1,
      anon_sym_null,
    ACTIONS(89), 1,
      aux_sym_variable_token1,
    ACTIONS(91), 1,
      anon_sym_LBRACE,
    ACTIONS(93), 1,
      anon_sym_LBRACK,
    ACTIONS(95), 1,
      anon_sym_if,
    STATE(7), 1,
      sym_boolean,
    STATE(84), 1,
      sym_identifier,
    ACTIONS(97), 2,
      sym_number,
      sym_string,
    ACTIONS(99), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 8,
      sym__expression,
      sym_literal,
      sym_variable,
      sym_function_call,
      sym_object,
      sym_array,
      sym_if_expression,
      sym_binary_expression,
  [947] = 10,
    ACTIONS(87), 1,
      anon_sym_null,
    ACTIONS(89), 1,
      aux_sym_variable_token1,
    ACTIONS(91), 1,
      anon_sym_LBRACE,
    ACTIONS(93), 1,
      anon_sym_LBRACK,
    ACTIONS(95), 1,
      anon_sym_if,
    STATE(7), 1,
      sym_boolean,
    STATE(84), 1,
      sym_identifier,
    ACTIONS(97), 2,
      sym_number,
      sym_string,
    ACTIONS(99), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 8,
      sym__expression,
      sym_literal,
      sym_variable,
      sym_function_call,
      sym_object,
      sym_array,
      sym_if_expression,
      sym_binary_expression,
  [987] = 3,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(25), 16,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_else,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_and,
      anon_sym_or,
  [1013] = 10,
    ACTIONS(7), 1,
      anon_sym_null,
    ACTIONS(9), 1,
      aux_sym_variable_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_if,
    STATE(43), 1,
      sym_boolean,
    STATE(88), 1,
      sym_identifier,
    ACTIONS(21), 2,
      sym_number,
      sym_string,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(44), 8,
      sym__expression,
      sym_literal,
      sym_variable,
      sym_function_call,
      sym_object,
      sym_array,
      sym_if_expression,
      sym_binary_expression,
  [1053] = 10,
    ACTIONS(7), 1,
      anon_sym_null,
    ACTIONS(9), 1,
      aux_sym_variable_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_if,
    STATE(43), 1,
      sym_boolean,
    STATE(88), 1,
      sym_identifier,
    ACTIONS(21), 2,
      sym_number,
      sym_string,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(54), 8,
      sym__expression,
      sym_literal,
      sym_variable,
      sym_function_call,
      sym_object,
      sym_array,
      sym_if_expression,
      sym_binary_expression,
  [1093] = 10,
    ACTIONS(7), 1,
      anon_sym_null,
    ACTIONS(9), 1,
      aux_sym_variable_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_if,
    STATE(43), 1,
      sym_boolean,
    STATE(88), 1,
      sym_identifier,
    ACTIONS(21), 2,
      sym_number,
      sym_string,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(51), 8,
      sym__expression,
      sym_literal,
      sym_variable,
      sym_function_call,
      sym_object,
      sym_array,
      sym_if_expression,
      sym_binary_expression,
  [1133] = 2,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(31), 16,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_else,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_and,
      anon_sym_or,
  [1156] = 2,
    ACTIONS(85), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(83), 16,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_else,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_and,
      anon_sym_or,
  [1179] = 2,
    ACTIONS(37), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 16,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_else,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_and,
      anon_sym_or,
  [1202] = 2,
    ACTIONS(53), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(51), 16,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_else,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_and,
      anon_sym_or,
  [1225] = 2,
    ACTIONS(73), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(71), 16,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_else,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_and,
      anon_sym_or,
  [1248] = 3,
    ACTIONS(136), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(79), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_else,
    ACTIONS(134), 11,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_and,
      anon_sym_or,
  [1273] = 2,
    ACTIONS(69), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(67), 16,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_else,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_and,
      anon_sym_or,
  [1296] = 2,
    ACTIONS(41), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(39), 16,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_else,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_and,
      anon_sym_or,
  [1319] = 2,
    ACTIONS(45), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(43), 16,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_else,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_and,
      anon_sym_or,
  [1342] = 2,
    ACTIONS(49), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(47), 16,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_else,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_and,
      anon_sym_or,
  [1365] = 2,
    ACTIONS(65), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(63), 16,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_else,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_and,
      anon_sym_or,
  [1388] = 2,
    ACTIONS(61), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(59), 16,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_else,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_and,
      anon_sym_or,
  [1411] = 2,
    ACTIONS(77), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(75), 16,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_else,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_and,
      anon_sym_or,
  [1434] = 5,
    ACTIONS(138), 1,
      anon_sym_COMMA,
    ACTIONS(140), 1,
      anon_sym_RBRACK,
    STATE(70), 1,
      aux_sym_function_call_repeat1,
    ACTIONS(136), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(134), 11,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_and,
      anon_sym_or,
  [1461] = 5,
    ACTIONS(138), 1,
      anon_sym_COMMA,
    ACTIONS(142), 1,
      anon_sym_RPAREN,
    STATE(68), 1,
      aux_sym_function_call_repeat1,
    ACTIONS(136), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(134), 11,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_and,
      anon_sym_or,
  [1488] = 3,
    ACTIONS(136), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(144), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
    ACTIONS(134), 11,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_and,
      anon_sym_or,
  [1511] = 5,
    ACTIONS(138), 1,
      anon_sym_COMMA,
    ACTIONS(146), 1,
      anon_sym_RBRACK,
    STATE(72), 1,
      aux_sym_function_call_repeat1,
    ACTIONS(136), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(134), 11,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_and,
      anon_sym_or,
  [1538] = 5,
    ACTIONS(138), 1,
      anon_sym_COMMA,
    ACTIONS(148), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      aux_sym_function_call_repeat1,
    ACTIONS(136), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(134), 11,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_and,
      anon_sym_or,
  [1565] = 3,
    ACTIONS(136), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(150), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    ACTIONS(134), 11,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_and,
      anon_sym_or,
  [1587] = 3,
    ACTIONS(152), 1,
      anon_sym_else,
    ACTIONS(136), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(134), 11,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_and,
      anon_sym_or,
  [1608] = 3,
    ACTIONS(154), 1,
      anon_sym_else,
    ACTIONS(136), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(134), 11,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_and,
      anon_sym_or,
  [1629] = 5,
    ACTIONS(156), 1,
      anon_sym_DASH_DASH_DASH,
    ACTIONS(158), 1,
      anon_sym_output,
    ACTIONS(160), 1,
      anon_sym_import,
    STATE(64), 1,
      sym_output_directive,
    STATE(65), 2,
      sym_import_directive,
      aux_sym_header_repeat1,
  [1646] = 5,
    ACTIONS(162), 1,
      aux_sym_variable_token1,
    ACTIONS(164), 1,
      anon_sym_RBRACE,
    ACTIONS(166), 1,
      sym_string,
    STATE(71), 1,
      sym_key_value_pair,
    STATE(86), 1,
      sym_identifier,
  [1662] = 5,
    ACTIONS(162), 1,
      aux_sym_variable_token1,
    ACTIONS(166), 1,
      sym_string,
    ACTIONS(168), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      sym_key_value_pair,
    STATE(86), 1,
      sym_identifier,
  [1678] = 4,
    ACTIONS(162), 1,
      aux_sym_variable_token1,
    ACTIONS(166), 1,
      sym_string,
    STATE(76), 1,
      sym_key_value_pair,
    STATE(86), 1,
      sym_identifier,
  [1691] = 3,
    ACTIONS(170), 1,
      anon_sym_COMMA,
    STATE(61), 1,
      aux_sym_function_call_repeat1,
    ACTIONS(144), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1702] = 3,
    ACTIONS(173), 1,
      anon_sym_DASH_DASH_DASH,
    ACTIONS(175), 1,
      anon_sym_import,
    STATE(62), 2,
      sym_import_directive,
      aux_sym_header_repeat1,
  [1713] = 3,
    ACTIONS(160), 1,
      anon_sym_import,
    ACTIONS(178), 1,
      anon_sym_DASH_DASH_DASH,
    STATE(62), 2,
      sym_import_directive,
      aux_sym_header_repeat1,
  [1724] = 3,
    ACTIONS(160), 1,
      anon_sym_import,
    ACTIONS(180), 1,
      anon_sym_DASH_DASH_DASH,
    STATE(63), 2,
      sym_import_directive,
      aux_sym_header_repeat1,
  [1735] = 3,
    ACTIONS(160), 1,
      anon_sym_import,
    ACTIONS(180), 1,
      anon_sym_DASH_DASH_DASH,
    STATE(62), 2,
      sym_import_directive,
      aux_sym_header_repeat1,
  [1746] = 3,
    ACTIONS(182), 1,
      anon_sym_COMMA,
    ACTIONS(184), 1,
      anon_sym_RBRACE,
    STATE(73), 1,
      aux_sym_object_repeat1,
  [1756] = 3,
    ACTIONS(138), 1,
      anon_sym_COMMA,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
    STATE(61), 1,
      aux_sym_function_call_repeat1,
  [1766] = 3,
    ACTIONS(138), 1,
      anon_sym_COMMA,
    ACTIONS(188), 1,
      anon_sym_RPAREN,
    STATE(61), 1,
      aux_sym_function_call_repeat1,
  [1776] = 3,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    ACTIONS(193), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      aux_sym_object_repeat1,
  [1786] = 3,
    ACTIONS(138), 1,
      anon_sym_COMMA,
    ACTIONS(195), 1,
      anon_sym_RBRACK,
    STATE(61), 1,
      aux_sym_function_call_repeat1,
  [1796] = 3,
    ACTIONS(182), 1,
      anon_sym_COMMA,
    ACTIONS(197), 1,
      anon_sym_RBRACE,
    STATE(74), 1,
      aux_sym_object_repeat1,
  [1806] = 3,
    ACTIONS(138), 1,
      anon_sym_COMMA,
    ACTIONS(199), 1,
      anon_sym_RBRACK,
    STATE(61), 1,
      aux_sym_function_call_repeat1,
  [1816] = 3,
    ACTIONS(182), 1,
      anon_sym_COMMA,
    ACTIONS(201), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      aux_sym_object_repeat1,
  [1826] = 3,
    ACTIONS(182), 1,
      anon_sym_COMMA,
    ACTIONS(203), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      aux_sym_object_repeat1,
  [1836] = 2,
    ACTIONS(162), 1,
      aux_sym_variable_token1,
    STATE(82), 1,
      sym_identifier,
  [1843] = 1,
    ACTIONS(193), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1848] = 1,
    ACTIONS(29), 2,
      anon_sym_from,
      anon_sym_COLON,
  [1853] = 1,
    ACTIONS(205), 2,
      anon_sym_DASH_DASH_DASH,
      anon_sym_import,
  [1858] = 1,
    ACTIONS(207), 2,
      anon_sym_DASH_DASH_DASH,
      anon_sym_import,
  [1863] = 1,
    ACTIONS(209), 1,
      ts_builtin_sym_end,
  [1867] = 1,
    ACTIONS(211), 1,
      sym_string,
  [1871] = 1,
    ACTIONS(213), 1,
      anon_sym_from,
  [1875] = 1,
    ACTIONS(215), 1,
      ts_builtin_sym_end,
  [1879] = 1,
    ACTIONS(217), 1,
      anon_sym_LPAREN,
  [1883] = 1,
    ACTIONS(219), 1,
      sym_number,
  [1887] = 1,
    ACTIONS(221), 1,
      anon_sym_COLON,
  [1891] = 1,
    ACTIONS(223), 1,
      sym_string,
  [1895] = 1,
    ACTIONS(225), 1,
      anon_sym_LPAREN,
  [1899] = 1,
    ACTIONS(227), 1,
      anon_sym_DASH_DASH_DASH,
  [1903] = 1,
    ACTIONS(229), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 31,
  [SMALL_STATE(6)] = 59,
  [SMALL_STATE(7)] = 87,
  [SMALL_STATE(8)] = 115,
  [SMALL_STATE(9)] = 143,
  [SMALL_STATE(10)] = 171,
  [SMALL_STATE(11)] = 199,
  [SMALL_STATE(12)] = 231,
  [SMALL_STATE(13)] = 259,
  [SMALL_STATE(14)] = 287,
  [SMALL_STATE(15)] = 315,
  [SMALL_STATE(16)] = 343,
  [SMALL_STATE(17)] = 371,
  [SMALL_STATE(18)] = 403,
  [SMALL_STATE(19)] = 431,
  [SMALL_STATE(20)] = 477,
  [SMALL_STATE(21)] = 523,
  [SMALL_STATE(22)] = 569,
  [SMALL_STATE(23)] = 615,
  [SMALL_STATE(24)] = 658,
  [SMALL_STATE(25)] = 701,
  [SMALL_STATE(26)] = 744,
  [SMALL_STATE(27)] = 787,
  [SMALL_STATE(28)] = 827,
  [SMALL_STATE(29)] = 867,
  [SMALL_STATE(30)] = 907,
  [SMALL_STATE(31)] = 947,
  [SMALL_STATE(32)] = 987,
  [SMALL_STATE(33)] = 1013,
  [SMALL_STATE(34)] = 1053,
  [SMALL_STATE(35)] = 1093,
  [SMALL_STATE(36)] = 1133,
  [SMALL_STATE(37)] = 1156,
  [SMALL_STATE(38)] = 1179,
  [SMALL_STATE(39)] = 1202,
  [SMALL_STATE(40)] = 1225,
  [SMALL_STATE(41)] = 1248,
  [SMALL_STATE(42)] = 1273,
  [SMALL_STATE(43)] = 1296,
  [SMALL_STATE(44)] = 1319,
  [SMALL_STATE(45)] = 1342,
  [SMALL_STATE(46)] = 1365,
  [SMALL_STATE(47)] = 1388,
  [SMALL_STATE(48)] = 1411,
  [SMALL_STATE(49)] = 1434,
  [SMALL_STATE(50)] = 1461,
  [SMALL_STATE(51)] = 1488,
  [SMALL_STATE(52)] = 1511,
  [SMALL_STATE(53)] = 1538,
  [SMALL_STATE(54)] = 1565,
  [SMALL_STATE(55)] = 1587,
  [SMALL_STATE(56)] = 1608,
  [SMALL_STATE(57)] = 1629,
  [SMALL_STATE(58)] = 1646,
  [SMALL_STATE(59)] = 1662,
  [SMALL_STATE(60)] = 1678,
  [SMALL_STATE(61)] = 1691,
  [SMALL_STATE(62)] = 1702,
  [SMALL_STATE(63)] = 1713,
  [SMALL_STATE(64)] = 1724,
  [SMALL_STATE(65)] = 1735,
  [SMALL_STATE(66)] = 1746,
  [SMALL_STATE(67)] = 1756,
  [SMALL_STATE(68)] = 1766,
  [SMALL_STATE(69)] = 1776,
  [SMALL_STATE(70)] = 1786,
  [SMALL_STATE(71)] = 1796,
  [SMALL_STATE(72)] = 1806,
  [SMALL_STATE(73)] = 1816,
  [SMALL_STATE(74)] = 1826,
  [SMALL_STATE(75)] = 1836,
  [SMALL_STATE(76)] = 1843,
  [SMALL_STATE(77)] = 1848,
  [SMALL_STATE(78)] = 1853,
  [SMALL_STATE(79)] = 1858,
  [SMALL_STATE(80)] = 1863,
  [SMALL_STATE(81)] = 1867,
  [SMALL_STATE(82)] = 1871,
  [SMALL_STATE(83)] = 1875,
  [SMALL_STATE(84)] = 1879,
  [SMALL_STATE(85)] = 1883,
  [SMALL_STATE(86)] = 1887,
  [SMALL_STATE(87)] = 1891,
  [SMALL_STATE(88)] = 1895,
  [SMALL_STATE(89)] = 1899,
  [SMALL_STATE(90)] = 1903,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 5, 0, 3),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 5, 0, 3),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 3, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 2),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 2),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 3),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, 0, 3),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 4, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 4, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 4, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 3),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 3),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 5, 0, 6),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 5, 0, 6),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [106] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [109] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [121] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_value_pair, 3, 0, 5),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 2, 0, 1),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [170] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_header_repeat1, 2, 0, 0),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_header_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 4, 0, 1),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 3, 0, 1),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [190] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_directive, 2, 0, 4),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_directive, 4, 0, 7),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [229] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_dataweave(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
